# -*- coding: utf-8 -*-
"""10Data Visualization3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kylDH1v_BM_YeS2CMldmb6igGWStLkXm
"""

import numpy as np
import pandas as pd

df = pd.read_csv("data10.csv")
df.columns = ["col1","col2","col3","col4","col5"]

df.head()

column = len(list(df))
column

"""1.List down the features and their types (e.g., numeric, nominal) available in the dataset."""

df.info()

"""Hence the dataset contains 4 numerical columns and 1 object column"""

np.unique(df["col5"])

df.describe()

"""Compute and display summary statistics for each feature available in the dataset."""

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
# %matplotlib inline

"""Data Visualization-Create a histogram for each feature in the dataset to illustrate the feature distributions. Plot each histogram."""

fig, axes = plt.subplots(2, 2, figsize=(16, 8))


axes[0,0].set_title("Distribution of First Column")
axes[0,0].hist(df["col1"]);

axes[0,1].set_title("Distribution of Second Column")
axes[0,1].hist(df["col2"]);

axes[1,0].set_title("Distribution of Third Column")
axes[1,0].hist(df["col3"]);

axes[1,1].set_title("Distribution of Fourth Column")
axes[1,1].hist(df["col4"]);

data_to_plot = [df["col1"],df["col2"],df["col3"],df["col4"]]

sns.set_style("whitegrid")
# Creating a figure instance
fig = plt.figure(1, figsize=(12,8))

# Creating an axes instance
ax = fig.add_subplot(111)

# Creating the boxplot
bp = ax.boxplot(data_to_plot)

"""Create a boxplot for each feature in the dataset. All of the boxplots should be combined into a single plot. Compare distributions and identify outliers.



If we observe closely. for the box 2, interquartile distance is roughly around 0.75 hence the values lying beyond this range of (third quartile + interquartile distance) i.e. roughly around 4.05 will be considered as outliers. Similarly outliers with other boxplots can be found
"""

sns.boxplot(x='col1', y='col2', data=df)

sns.boxplot(x='col3', y='col4', data=df)

This notebook performs Exploratory Data Analysis (EDA) and Data Visualization on a dataset that appears to be the famous Iris Dataset (though renamed here with generic column names).

Below is a breakdown of the theory, the steps involved, a line-by-line explanation of the code, and the requirements to run it.

1. Theoretical Concepts & Steps
The notebook follows a standard data science workflow for initial data inspection:

Step 1: Data Loading and Cleaning: Importing necessary libraries and loading the raw data from a CSV file into a structured format (DataFrame).

Step 2: Structural Analysis: Checking the shape, column names, and data types (Numeric vs. Nominal).

Numeric: Variables representing measurable quantities (e.g., 5.1 cm).

Nominal/Categorical: Variables representing groups or labels (e.g., "Iris-setosa").

Step 3: Descriptive Statistics: Using mathematical summaries (mean, standard deviation, quartiles) to understand the central tendency and spread of the data.

Step 4: Data Visualization: * Histograms: Used to see the distribution of data. It helps identify if data is normally distributed, skewed, or has gaps.

Boxplots: Used to visualize the dispersion and detect outliers. A boxplot shows the median, the Interquartile Range (IQR), and "whiskers" that extend to show the rest of the distribution.

2. Line-by-Line Code Explanation
Cell 1 & 2: Initialization
Python
import numpy as np
import pandas as pd
df = pd.read_csv("data10.csv")
df.columns = ["col1","col2","col3","col4","col5"]
import numpy as np: Imports the Numerical Python library for mathematical operations.

import pandas as pd: Imports the Pandas library, used for data manipulation and analysis.

df = pd.read_csv(...): Loads the file data10.csv into a variable df (DataFrame).

df.columns = [...]: Manually renames the five columns to col1 through col5.

Cell 3 & 4: Basic Inspection
Python
df.head()
column = len(list(df))
df.head(): Displays the first 5 rows of the dataset to verify it loaded correctly.

len(list(df)): Converts the column headers to a list and calculates the length (number of columns).

Cell 5 & 6: Data Types and Unique Values
Python
df.info()
np.unique(df["col5"])
df.info(): Prints a summary of the DataFrame, including the number of entries, whether there are null (missing) values, and the memory usage.

np.unique(df["col5"]): Finds and lists the unique categories in the target column (e.g., the species names).

Cell 7: Summary Statistics
Python
df.describe()
Generates a table showing the count, mean, std (standard deviation), min, max, and the 25%, 50% (median), and 75% percentiles for all numerical columns.

Cell 9: Distribution Plotting (Histograms)
Python
fig, axes = plt.subplots(2, 2, figsize=(16, 8))
axes[0,0].set_title("Distribution of First Column")
axes[0,0].hist(df["col1"]);
...
plt.subplots(2, 2, ...): Creates a grid of 4 plots (2 rows, 2 columns).

axes[0,0].hist(...): Plots a histogram for the first column in the top-left quadrant.

set_title: Adds a label to the specific plot.

Cell 10: Dispersion Plotting (Boxplots)
Python
data_to_plot = [df["col1"],df["col2"],df["col3"],df["col4"]]
fig = plt.figure(1, figsize=(12,8))
ax = fig.add_subplot(111)
bp = ax.boxplot(data_to_plot)
data_to_plot: Creates a list of the four numerical columns.

fig.add_subplot(111): Creates a single large plot area.

ax.boxplot(...): Draws box-and-whisker plots for all four columns side-by-side. This allows for direct comparison of the scales and ranges of different features.

3. Requirements to Run This Code
To run this notebook successfully on your local machine, you need the following:

Python Environment: Python 3.x installed (preferably via Anaconda or a virtual environment).

Libraries: You must install the following packages via terminal/command prompt:

pip install pandas numpy matplotlib seaborn

Data File: You must have the file named data10.csv in the same folder as the notebook. The code specifically looks for this file name.

Jupyter Interface: You need Jupyter Notebook or JupyterLab (or an IDE like VS Code or PyCharm with Jupyter support) to open the .ipynb file.



WHAT IS JUPYTER NOTEBOOK IN SHORT

Jupyter Notebook is an open-source web application used for creating and sharing documents that contain live code, equations, visualizations, and narrative text. In the context of data science and Python programming, it serves as an interactive environment for data cleaning, transformation, numerical simulation, statistical modeling, and data visualization.

Key Features and Workflow
Interactive Development: It allows users to write and execute code (typically Python) in discrete "cells," providing immediate feedback and output.

Narrative Support: It supports Markdown cells, enabling users to explain their methodology, theory, and steps in regular prose alongside their code.

Data Visualization: It integrates libraries like Matplotlib and Seaborn to display graphs and charts directly within the document.

Structural Analysis: It provides tools to inspect data structures, such as checking data types (numeric vs. nominal) and descriptive statistics (mean, standard deviation, and quartiles).

Requirements to Run
To use Jupyter Notebook locally, you generally require:

Python Environment: A Python 3.x installation.

Libraries: Standard data science packages including Pandas, NumPy, Matplotlib, and Seaborn.

Interface: The Jupyter application itself or an IDE with Jupyter support (such as VS Code or PyCharm) to open .ipynb files.


ADVANTAGES , DISADVANTAGES, AND REAL LIFE APPLICATIONS? OF THIS PRACTICAL
Based on the provided notebook, this practical focuses on Exploratory Data Analysis (EDA) and Data Visualization using Python libraries like Pandas, Matplotlib, and Seaborn.

Advantages
Identification of Data Distribution: Histograms allow for a quick visual assessment of how data is spread across different ranges for each feature.

Outlier Detection: Boxplots are effectively used to identify data points that fall significantly outside the expected range (Interquartile Range), which is crucial for data cleaning.

Rapid Data Summarization: Functions like df.describe() and df.info() provide immediate insights into the dataset’s central tendencies (mean, median), scale, and missing values without manual calculation.

Comparison of Features: Visualizing multiple features together in boxplots helps in comparing the scales and variances of different variables at once.

Disadvantages
Loss of Detail: While boxplots provide a great summary of dispersion, they can hide the actual shape of the distribution (such as bimodal data) that a histogram would otherwise reveal.

Limited Multi-dimensional Insight: The current practical primarily uses univariate or bivariate analysis (one or two variables at a time); it may struggle to show complex, hidden relationships between three or more variables simultaneously.

Sensitivity to Scale: If the axis scales are not chosen carefully, visualizations can inadvertently exaggerate or minimize differences between data groups.

Real-Life Applications
Scientific Research (Botany): As demonstrated with the Iris-like dataset, these techniques are used to classify plant species based on physical measurements like petal and sepal length.

Quality Control in Manufacturing: Engineers use histograms and boxplots to monitor product dimensions and detect defects or outliers in a production line.

Healthcare and Medicine: Researchers use these methods to analyze patient vitals (e.g., blood pressure, cholesterol levels) to identify health trends across different demographic groups.

Financial Risk Management: Analysts use data visualization to detect unusual patterns or outliers in transaction data, which can help in identifying potential fraud.