# -*- coding: utf-8 -*-
"""4Linear_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fvqOCChdr7NqdsVq_MdR7W0S0a-W4W9S

# Simple Linear Regression
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Load Boston housing dataset
data = pd.read_csv('data4.csv')
X = data.iloc[:, 0].values.reshape(-1, 1)  # Reshape X to 2D
y = data.iloc[:, 1].values

X

y

# Split data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

# Create a Linear Regression model
model = LinearRegression()
model.fit(x_train, y_train)

# Make predictions
y_pred = model.predict(x_test)

# Model Evaluation Metrics
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

# Print model parameters
print(f'Intercept: {model.intercept_}')
print(f'Coefficient: {model.coef_[0]}')
print(f'Mean Squared Error: {mse}')
print(f'Root Mean Squared Error (RMSE): {rmse}')
print(f'R-Squared Score (R²): {r2}')

# User input for price and predicting area
user_price = float(input("Enter the house price : "))
predicted_area = (model.intercept_ + model.coef_[0] * user_price)
print(f'Predicted area : {predicted_area}')

Simple Linear Regression — Complete Theory + Steps + Code Explanation

Your notebook is based on Simple Linear Regression using Python and Machine Learning libraries.

1. What is Linear Regression?

Linear Regression is a supervised machine learning algorithm used to predict continuous values.

It finds a relationship between:

Independent Variable (X) → Input
Dependent Variable (Y) → Output

Example:

House Price	House Area
20 lakh	800 sq ft
30 lakh	1200 sq ft

The model learns the relation between them.

2. Goal of Your Program

Your code:

Reads dataset from CSV file
Splits data into training and testing
Trains Linear Regression model
Predicts values
Calculates accuracy
Takes user input
Predicts area from price
3. Real Life Applications

Linear Regression is used in:

House price prediction
Salary prediction
Weather forecasting
Sales prediction
Stock trend analysis
Demand forecasting
4. Formula Used in Linear Regression

The basic equation is:

y=mx+c
m
b
-10
-8
-6
-4
-2
2
4
6
8
10
-10
-5
5
10
y-intercept
x-intercept

Where:

y = predicted output
x = input feature
m = slope/coefficient
c = intercept

Example:

If equation becomes:

y=2x+5

For x=3:

y=2(3)+5=11
5. Steps of Linear Regression
Step 1 — Import Libraries

Libraries provide ready-made functions.

Step 2 — Load Dataset

Read CSV file into pandas dataframe.

Step 3 — Separate Input and Output
X → independent variable
y → dependent variable
Step 4 — Split Dataset

Training data → teaches model
Testing data → checks performance

Step 5 — Create Model

Create Linear Regression object.

Step 6 — Train Model

Model learns pattern from training data.

Step 7 — Predict Values

Predict output for testing data.

Step 8 — Evaluate Model

Calculate errors and accuracy.

Step 9 — Take User Input

User enters value.

Step 10 — Predict Final Output

Model predicts result using learned equation.

6. Line-by-Line Code Explanation
Importing Libraries
import numpy as np
Meaning

Imports NumPy library.

Use

Used for:

Mathematical calculations
Arrays
Square root
import pandas as pd
Meaning

Imports pandas library.

Use

Used for:

Reading CSV files
Data handling
Tables/dataframes
from sklearn.linear_model import LinearRegression
Meaning

Imports Linear Regression model from scikit-learn.

Use

Used to create regression model.

from sklearn.model_selection import train_test_split
Meaning

Imports function to split dataset.

Use

Separates training and testing data.

from sklearn.metrics import mean_squared_error, r2_score
Meaning

Imports evaluation metrics.

Use

Used to calculate:

MSE
RMSE
R² score
Loading Dataset
data = pd.read_csv('data4.csv')
Meaning

Reads CSV file.

Example Dataset
Price	Area
20	800
30	1200
Selecting Input and Output
X = data.iloc[:, 0].values.reshape(-1, 1)
Meaning

Selects first column as input feature.

Breaking It
data.iloc[:,0]
: means all rows
0 means first column
.values

Converts dataframe column into NumPy array.

.reshape(-1,1)

Converts 1D array into 2D array.

Why?

Scikit-learn expects 2D input.

Example:

Before reshape:

[10,20,30]

After reshape:

[[10],
 [20],
 [30]]
y = data.iloc[:, 1].values
Meaning

Selects second column as output.

Viewing Data
X

Displays input values.

y

Displays output values.

Splitting Dataset
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)
Meaning

Splits dataset into:

Training data
Testing data
Parameters
test_size=0.2

20% data used for testing.

80% used for training.

random_state=2

Ensures same split every time program runs.

Creating Model
model = LinearRegression()
Meaning

Creates Linear Regression object.

Training Model
model.fit(x_train, y_train)
Meaning

Trains model using training data.

Internally

Model calculates:

Best slope
Best intercept

to fit line.

Predicting Values
y_pred = model.predict(x_test)
Meaning

Predicts output for testing data.

Evaluation Metrics
mse = mean_squared_error(y_test, y_pred)
Meaning

Calculates Mean Squared Error.

Formula

MSE=
n
1
	​

∑(y
i
	​

−
y
i
	​

^
	​

)
2

Lower MSE = better model.

rmse = np.sqrt(mse)
Meaning

Calculates Root Mean Squared Error.

Formula

RMSE=
MSE
	​


r2 = r2_score(y_test, y_pred)
Meaning

Calculates R² score.

Formula

R
2
=1−
SS
tot
	​

SS
res
	​

	​


Interpretation
R² Value	Meaning
1	Perfect prediction
0	Poor prediction

Higher R² = better model.

Printing Results
print(f'Intercept: {model.intercept_}')
Meaning

Prints intercept c.

print(f'Coefficient: {model.coef_[0]}')
Meaning

Prints slope m.

print(f'Mean Squared Error: {mse}')

Prints MSE.

print(f'Root Mean Squared Error (RMSE): {rmse}')

Prints RMSE.

print(f'R-Squared Score (R²): {r2}')

Prints R² accuracy score.

User Input Section
user_price = float(input("Enter the house price : "))
Meaning

Takes price from user.

float() converts input into decimal number.

Prediction Formula
predicted_area = (model.intercept_ + model.coef_[0] * user_price)
Meaning

Uses regression equation:

y=mx+c

to predict area.

Final Output
print(f'Predicted area : {predicted_area}')

Displays predicted area.

7. Requirements to Run This Program

You need:

Software
1. Python Installed

Recommended:

Python 3.10+
2. Jupyter Notebook OR VS Code

You are using .ipynb notebook.

Can run using:

Jupyter Notebook
Google Colab
VS Code
8. Required Libraries

Install using:

pip install numpy pandas scikit-learn
9. Required Dataset

You need:

data4.csv

inside same folder.

10. Expected CSV Format

Example:

Price	Area
20	800
25	1000
30	1200
11. Algorithm of Your Program
Algorithm
Start
Import libraries
Load CSV dataset
Separate X and y
Split dataset
Create Linear Regression model
Train model
Predict test outputs
Calculate MSE, RMSE, R²
Display results
Take user input
Predict final value
Display prediction
Stop
12. Time Complexity
Operation	Complexity
Reading data	O(n)
Training model	O(n)
Prediction	O(n)

Overall:

O(n)
13. Space Complexity
O(n)

because data is stored in memory.

14. Viva Questions You May Be Asked
Basic Questions
What is Linear Regression?

A supervised learning algorithm used for predicting continuous values.

What is dependent variable?

Output variable.

What is independent variable?

Input variable.

Why reshape is used?

Because sklearn requires 2D input.

Why split dataset?

To train and test model separately.

What is overfitting?

When model memorizes training data and performs poorly on new data.

What is R² score?

Measures accuracy of regression model.

Difference between MSE and RMSE?
MSE gives squared error
RMSE gives error in original unit
What does fit() do?

Trains the model.

What does predict() do?

Predicts output using trained model.

15. Short Viva Explanation

You can explain like this:

“This program implements Simple Linear Regression using Python and scikit-learn. First we import libraries and load CSV data. Then we separate input and output variables. After that we split data into training and testing sets. We create and train Linear Regression model using fit() function. Then we predict outputs using predict(). Finally we calculate evaluation metrics like MSE, RMSE, and R² score and take user input for prediction.”