# -*- coding: utf-8 -*-
"""5Logistic_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yRdsXn0zijCM1qYsGHgro6ZtmjK4mmi2
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

# Load dataset
df = pd.read_csv('data5.csv')

# Drop 'Gender' column
df1 = df.drop("Genre", axis=1)

# Define features and target variable
y = df1.iloc[:, -1].values  # Target variable
X = df1.iloc[:, :-1].values  # Feature set

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=2)

# Train Logistic Regression model
LR = LogisticRegression()
LR.fit(X_train, y_train)

# Compute confusion matrix
y_pred = LR.predict(X_test)
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()  #.ravel() converts the 2x2 matrix into a 1D array.

# Calculate metrics
accuracy = (tn + tp) * 100 / (tp + tn + fp + fn)
precision = tp / (tp + fp)
recall = tp / (tp + fn)
f1_score = (2 * precision * recall) / (precision + recall)
specificity = tn / (tn + fp)

# Display metrics
print(f"Accuracy: {accuracy:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1_score:.2f}")
print(f"Specificity: {specificity:.2f}")

# Take user input for feature values
print("Enter values for the following features (Cust_ID, Age, Income):")
input_features = []
for i in range(3):
    val = float(input(f"Feature {i+1}: "))
    input_features.append(val)

# Convert input into numpy array and reshape
input_array = np.array(input_features).reshape(1, -1)  #reshaped into a 2D array (1 row and multiple col)

# Make prediction
prediction = LR.predict(input_array)[0]
print(f"Predicted Output: {prediction}")

Logistic Regression — Complete Theory + Steps + Line-by-Line Code Explanation

Your notebook is implementing Logistic Regression using Python and Machine Learning libraries.

The program:

Loads a dataset
Trains a Logistic Regression model
Tests the model
Calculates performance metrics
Takes user input
Predicts output
1. What is Logistic Regression?

Machine Learning

Logistic Regression is a Supervised Machine Learning Classification Algorithm.

It is mainly used for:

YES/NO prediction
TRUE/FALSE prediction
0/1 classification

Examples:

Spam or Not Spam
Disease or No Disease
Pass or Fail
Fraud or Not Fraud
2. Why is it called “Regression” if it is used for Classification?

Because mathematically it uses a regression equation internally.

But final output is converted into classes using the Sigmoid Function.

3. Theory of Logistic Regression
Main Idea

The algorithm:

Learns patterns from training data
Calculates probability
Converts probability into class label
4. Sigmoid Function

This is the heart of Logistic Regression.

It converts values between:

0 to 1

Widget for sigmoid-related graphable function:

y=
1+e
−x
1
	​

Interpretation
Probability close to 1 → Positive class
Probability close to 0 → Negative class

Example:

0.85 → YES
0.10 → NO
5. Steps of Logistic Regression
Step 1 — Collect Dataset

Example:

Age	Income	Purchased
22	30000	0
45	80000	1
Step 2 — Preprocess Data
Remove unwanted columns
Handle missing values
Convert categorical data
Step 3 — Split Dataset

Dataset divided into:

Training Data
Testing Data

Usually:

75% training
25% testing
Step 4 — Train Model

Model learns relationship between:

Features (X)
Target (Y)
Step 5 — Predict Output

Model predicts class labels.

Step 6 — Evaluate Model

Using:

Accuracy
Precision
Recall
F1 Score
Specificity
6. Complete Code Explanation (Line by Line)
Import Libraries
import pandas as pd
Meaning

Imports Pandas library.

Use

Used for:

Reading CSV files
Handling tables/dataframes
import numpy as np
Meaning

Imports NumPy library.

Use

Used for:

Arrays
Mathematical operations
from sklearn.model_selection import train_test_split
Meaning

Imports function to split dataset.

Use

Separates data into:

Training set
Testing set
from sklearn.linear_model import LogisticRegression
Meaning

Imports Logistic Regression algorithm.

from sklearn.metrics import confusion_matrix
Meaning

Imports confusion matrix function.

Use

Used to evaluate model performance.

Load Dataset
df = pd.read_csv('data5.csv')
Meaning

Reads CSV file into dataframe.

Example:

Dataset stored in data5.csv
Drop Column
df1 = df.drop("Genre", axis=1)
Meaning

Removes "Genre" column.

Why?

Maybe:

Unnecessary
Non-numeric
Not useful for prediction
Define Features and Target
y = df1.iloc[:, -1].values
Meaning

Stores last column as target variable.

Example

Purchased:

0
1
X = df1.iloc[:, :-1].values
Meaning

Stores all columns except last as features.

Features Example
Age
Salary
Income
Dataset Splitting
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=2)
Meaning

Splits data:

75% training
25% testing
Parameters
test_size=0.25

25% data for testing.

random_state=2

Ensures same split every time program runs.

Create Model
LR = LogisticRegression()
Meaning

Creates Logistic Regression object.

Train Model
LR.fit(X_train, y_train)
Meaning

Model learns from training data.

Internally

It finds best mathematical boundary between classes.

Prediction
y_pred = LR.predict(X_test)
Meaning

Predicts outputs for test data.

Confusion Matrix
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
Meaning

Calculates:

True Negative
False Positive
False Negative
True Positive
Confusion Matrix Table
Actual / Predicted	Positive	Negative
Positive	TP	FN
Negative	FP	TN
.ravel()

Converts matrix into single array.

Example:

Before:

[[50 2]
 [3 45]]

After:

50, 2, 3, 45
Accuracy
accuracy = (tn + tp) * 100 / (tp + tn + fp + fn)
Formula

Accuracy=
TP+TN+FP+FN
TP+TN
	​

×100

Meaning

How many predictions are correct.

Precision
precision = tp / (tp + fp)
Formula

Precision=
TP+FP
TP
	​


Meaning

Out of predicted positives, how many are actually positive.

Recall
recall = tp / (tp + fn)
Formula

Recall=
TP+FN
TP
	​


Meaning

Out of actual positives, how many correctly predicted.

F1 Score
f1_score = (2 * precision * recall) / (precision + recall)
Formula

F1=
Precision+Recall
2×Precision×Recall
	​


Meaning

Balance between precision and recall.

Specificity
specificity = tn / (tn + fp)
Formula

Specificity=
TN+FP
TN
	​


Meaning

How well model identifies negatives.

Print Metrics
print(f"Accuracy: {accuracy:.2f}%")
Meaning

Displays accuracy with 2 decimal places.

Same for:

Precision
Recall
F1 Score
Specificity
User Input
print("Enter values for the following features (Cust_ID, Age, Income):")
Meaning

Asks user to enter feature values.

Empty List
input_features = []

Stores user inputs.

Loop
for i in range(3):

Runs 3 times for:

Cust_ID
Age
Income
Taking Input
val = float(input(f"Feature {i+1}: "))
Meaning

Takes input from user as decimal number.

Add to List
input_features.append(val)

Adds values into list.

Convert to NumPy Array
input_array = np.array(input_features).reshape(1, -1)
Meaning

Converts list into 2D array.

Why reshape?

Machine learning models expect:

Rows = samples
Columns = features

Example:

[[101, 25, 50000]]
Final Prediction
prediction = LR.predict(input_array)[0]
Meaning

Predicts class for user input.

Display Prediction
print(f"Predicted Output: {prediction}")

Displays final output.

7. Requirements to Run This Program

You need:

Software Required
Python

Install Python 3.x

Python Official Website

Libraries Required

Install using terminal:

pip install pandas numpy scikit-learn
8. Required Files

You need:

Python file / notebook
Dataset file (data5.csv)

Both should be in same folder.

9. Flow of Entire Program
Dataset
   ↓
Preprocessing
   ↓
Train-Test Split
   ↓
Train Logistic Regression
   ↓
Prediction
   ↓
Evaluation Metrics
   ↓
User Input Prediction
10. Real Life Applications
Logistic Regression Applications
Email Spam Detection
Disease Prediction
Fraud Detection
Customer Purchase Prediction
Bank Loan Approval
Employee Attrition Prediction


11. Advantages
Simple
Fast
Easy to interpret
Works well for binary classification
12. Limitations
Works best for linear data
Not suitable for highly complex patterns
Sensitive to outliers
13. Time Complexity
Training
O(n×m)

Where:

n = number of samples
m = number of features
14. Space Complexity
O(m)

Where:

m = number of features
15. How to Explain in Viva

You can say:

“This project uses Logistic Regression, a supervised machine learning classification algorithm. The dataset is first loaded and preprocessed. Then it is divided into training and testing data. The Logistic Regression model is trained using training data and predictions are made on testing data. Performance is evaluated using accuracy, precision, recall, F1-score, and specificity. Finally, the model predicts output for new user-entered values.”