# -*- coding: utf-8 -*-
"""6Naïve_Bayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11pfGoY1qlcjY_8aM1ahFtxFKd7gPjKwu

# Naive Bayes

## Importing the libraries
"""

import numpy as np
import pandas as pd

"""## Importing the dataset"""

dataset = pd.read_csv('data6.csv')
dataset

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 2)

"""## Training the Naive Bayes model on the Training set"""

from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

"""## Predicting the Test set results"""

y_pred = classifier.predict(X_test)
y_pred

# Evaluate the performance of Model for train_y and
from sklearn.metrics import precision_score,confusion_matrix,accuracy_score,recall_score
accuracy = accuracy_score(y_test,y_pred)
precision =precision_score(y_test, y_pred,average='micro')
recall = recall_score(y_test, y_pred,average='micro')
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")

"""## Making the Confusion Matrix"""

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
# Display the confusion matrix and evaluation metrics
print("Confusion Matrix:")
print(cm)

# Accept user input for prediction
age = float(input("Enter age: "))
salary = float(input("Enter salary: "))

# Reshape the input to a 2D array
input_data = [[age, salary]]

# Make the prediction
prediction = classifier.predict(input_data)

print(f"The predicted class for age {age} and salary {salary} is: {prediction[0]}")

# Naive Bayes Algorithm – Complete Theory, Steps, and Line-by-Line Code Explanation

# 1. What is Naive Bayes?

Naive Bayes is a supervised Machine Learning classification algorithm.
It is mainly used for:

* Prediction
* Classification
* Probability based decision making

Examples:

* Spam email detection
* Disease prediction
* Sentiment analysis
* Recommendation systems
* Customer purchase prediction

It is called:

* **Naive** because it assumes all features are independent.
* **Bayes** because it uses Bayes Theorem.

---

# 2. What is Supervised Learning?

In supervised learning:

* We already have input data and output labels.
* The model learns from labeled data.
* Then it predicts outputs for new data.

Example:

| Age | Salary | Purchased |
| --- | ------ | --------- |
| 22  | 25000  | No        |
| 35  | 60000  | Yes       |

Here:

* Age and Salary = Input Features
* Purchased = Output Label

---

# 3. Bayes Theorem

Naive Bayes works using Bayes Theorem.

The formula is:

genui{"math_block_widget_always_prefetch_v2":{"content":"P(A|B)=\frac{P(B|A)P(A)}{P(B)}"}}

Where:

* P(A|B) = Probability of A when B has occurred
* P(B|A) = Probability of B when A has occurred
* P(A) = Prior probability of A
* P(B) = Probability of B

---

# 4. Why is it Called “Naive”?

Because it assumes:

"Every feature is independent from every other feature"

Example:

* Age and salary are assumed independent.
* In real life this may not be true.
* But the algorithm still performs very well.

---

# 5. Types of Naive Bayes

## 1. Gaussian Naive Bayes

Used for continuous values.
Example:

* Age
* Salary
* Height
* Weight

Your program uses Gaussian Naive Bayes.

## 2. Multinomial Naive Bayes

Used for text classification.
Example:

* Word counts
* Spam detection

## 3. Bernoulli Naive Bayes

Used for binary values.
Example:

* True/False
* Yes/No

---

# 6. Real Life Applications

## Email Spam Detection

Classifies email as:

* Spam
* Not Spam

## Medical Diagnosis

Predicts disease based on symptoms.

## Sentiment Analysis

Classifies review as:

* Positive
* Negative

## Recommendation Systems

Recommends products or movies.

## Fraud Detection

Detects suspicious transactions.

---

# 7. Advantages of Naive Bayes

* Simple and fast
* Easy to implement
* Works well with small datasets
* Good for classification problems
* Requires less training data

---

# 8. Disadvantages of Naive Bayes

* Assumes feature independence
* Less accurate for highly complex datasets
* Zero frequency problem may occur

---

# 9. Complete Flow of Your Program

The complete process is:

1. Import libraries
2. Load dataset
3. Separate input and output
4. Split dataset into train and test data
5. Train Naive Bayes model
6. Predict results
7. Evaluate model
8. Create confusion matrix
9. Take user input
10. Predict output for user input

---

# 10. Dataset Used in Your Program

The file used is:

```python
 data6.csv
```

It probably contains:

| Age | Salary | Purchased |
| --- | ------ | --------- |
| 22  | 25000  | 0         |
| 35  | 60000  | 1         |

Where:

* Age and Salary = Features
* Purchased = Target Variable

---

# 11. Full Line-by-Line Code Explanation

# Step 1: Importing Libraries

```python
import numpy as np
import pandas as pd
```

## Explanation

### import numpy as np

* NumPy is used for numerical operations.
* It works with arrays and mathematical calculations.
* np is an alias (short name).

Example:

```python
arr = np.array([1,2,3])
```

### import pandas as pd

* Pandas is used for handling datasets.
* It helps in reading CSV files.
* pd is a shortcut name.

Example:

```python
data = pd.read_csv('file.csv')
```

---

# Step 2: Importing Dataset

```python
dataset = pd.read_csv('data6.csv')
dataset
```

## Explanation

### pd.read_csv('data6.csv')

* Reads CSV file.
* Loads dataset into memory.

### dataset =

Stores data inside variable named dataset.

### dataset

Displays dataset table.

---

# Step 3: Separating Features and Target Variable

```python
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
```

## Important Theory

Machine learning data has:

* Features (inputs)
* Labels (outputs)

Example:

| Age | Salary | Purchased |
| --- | ------ | --------- |
| 22  | 25000  | 0         |

Features:

* Age
* Salary

Label:

* Purchased

---

## Explanation of Code

### dataset.iloc

Used for integer-location indexing.

### X = dataset.iloc[:, :-1].values

Meaning:

* : → all rows
* :-1 → all columns except last

So X stores input features.

Example:

```python
[[22,25000],
 [35,60000]]
```

### .values

Converts dataframe into NumPy array.

---

### y = dataset.iloc[:, -1].values

Meaning:

* : → all rows
* -1 → last column

Stores output labels.

Example:

```python
[0,1,0,1]
```

---

# Step 4: Splitting Dataset

```python
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.25,
    random_state = 2
)
```

---

# Theory of Train-Test Split

Dataset is divided into:

## Training Set

Used to train model.

## Testing Set

Used to test model performance.

---

# Why Split Data?

If we test using same training data:

* Model may memorize answers.
* Accuracy becomes misleading.

Testing on unseen data gives real performance.

---

# Explanation of Code

## from sklearn.model_selection import train_test_split

Imports train-test splitting function.

---

## train_test_split()

Splits data into training and testing parts.

---

## test_size = 0.25

Means:

* 25% data for testing
* 75% data for training

---

## random_state = 2

Used for reproducibility.

Same random split every time.

---

# Step 5: Training Naive Bayes Model

```python
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)
```

---

# Theory of Gaussian Naive Bayes

Gaussian Naive Bayes assumes:

* Data follows normal distribution.

Normal distribution looks like a bell curve.

genui{"math_block_widget_always_prefetch_v2":{"content":"f(x)=\frac{1}{\sigma\sqrt{2\pi}}e^{-\frac{(x-\mu)^2}{2\sigma^2}}"}}

Where:

* μ = mean
* σ = standard deviation

---

# Explanation of Code

## from sklearn.naive_bayes import GaussianNB

Imports Gaussian Naive Bayes model.

---

## classifier = GaussianNB()

Creates Naive Bayes object.

---

## classifier.fit(X_train, y_train)

Trains model using training data.

The model learns patterns between:

* Inputs
* Outputs

---

# Step 6: Predicting Test Results

```python
y_pred = classifier.predict(X_test)
y_pred
```

---

# Explanation

## classifier.predict(X_test)

Predicts output for test data.

Example:

```python
[0,1,1,0]
```

---

## y_pred

Displays predicted outputs.

---

# Step 7: Evaluating Model

```python
from sklearn.metrics import precision_score, confusion_matrix, accuracy_score, recall_score

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='micro')
recall = recall_score(y_test, y_pred, average='micro')

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
```

---

# Evaluation Metrics Theory

## 1. Accuracy

Measures overall correctness.

Formula:

genui{"math_block_widget_always_prefetch_v2":{"content":"Accuracy=\frac{TP+TN}{TP+TN+FP+FN}"}}

Where:

* TP = True Positive
* TN = True Negative
* FP = False Positive
* FN = False Negative

---

## 2. Precision

Measures how many predicted positives are actually correct.

Formula:

genui{"math_block_widget_always_prefetch_v2":{"content":"Precision=\frac{TP}{TP+FP}"}}

---

## 3. Recall

Measures how many actual positives are correctly predicted.

Formula:

genui{"math_block_widget_always_prefetch_v2":{"content":"Recall=\frac{TP}{TP+FN}"}}

---

# Explanation of Code

## from sklearn.metrics import ...

Imports evaluation metrics.

---

## accuracy_score(y_test, y_pred)

Compares actual and predicted values.

---

## precision_score()

Calculates precision.

---

## recall_score()

Calculates recall.

---

## average='micro'

Used for multi-class calculations.

---

# Step 8: Confusion Matrix

```python
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)
```

---

# What is Confusion Matrix?

A table showing:

* Correct predictions
* Wrong predictions

Example:

| Actual/Predicted | Yes | No |
| ---------------- | --- | -- |
| Yes              | TP  | FN |
| No               | FP  | TN |

---

# Explanation

## confusion_matrix(y_test, y_pred)

Compares:

* Actual output
* Predicted output

Creates matrix.

---

# Step 9: User Input Prediction

```python
age = float(input("Enter age: "))
salary = float(input("Enter salary: "))
```

---

# Explanation

## input()

Takes input from user.

---

## float()

Converts input into decimal number.

Example:

```python
25 → 25.0
```

---

# Step 10: Reshaping Input

```python
input_data = [[age, salary]]
```

---

# Why Double Brackets?

Machine learning models expect 2D input.

Correct format:

```python
[[22,25000]]
```

Wrong format:

```python
[22,25000]
```

---

# Step 11: Prediction

```python
prediction = classifier.predict(input_data)
```

---

# Explanation

Model predicts output for entered values.

Example:

```python
[1]
```

Meaning:

* Purchased = Yes

---

# Step 12: Display Result

```python
print(f"The predicted class for age {age} and salary {salary} is: {prediction[0]}")
```

---

# Explanation

## f-string

Used for formatted printing.

Example:

```python
name = "Areeba"
print(f"Hello {name}")
```

Output:

```python
Hello Areeba
```

---

# 12. Algorithm of Naive Bayes

## Step-by-Step Algorithm

1. Start
2. Import libraries
3. Load dataset
4. Separate input and output
5. Split dataset into training and testing sets
6. Train Gaussian Naive Bayes model
7. Predict test outputs
8. Calculate accuracy, precision, recall
9. Generate confusion matrix
10. Take user input
11. Predict class for user data
12. Display result
13. Stop

---

# 13. Time Complexity

## Training Complexity

Approximately:

O(n × d)

Where:

* n = number of samples
* d = number of features

---

## Prediction Complexity

O(d)

Very fast prediction.

---

# 14. Space Complexity

O(d)

Stores probabilities and statistics.

---

# 15. Viva Questions and Answers

## Q1. What is Naive Bayes?

A probability-based supervised classification algorithm.

## Q2. Why is it called Naive?

Because it assumes features are independent.

## Q3. Which theorem is used?

Bayes Theorem.

## Q4. What is Gaussian Naive Bayes?

A Naive Bayes algorithm used for continuous data.

## Q5. Why do we split dataset?

To test model on unseen data.

## Q6. What is overfitting?

When model memorizes training data and performs poorly on new data.

## Q7. What is confusion matrix?

A matrix showing correct and incorrect predictions.

## Q8. What is accuracy?

Percentage of correct predictions.

## Q9. What is precision?

Correct positive predictions out of total predicted positives.

## Q10. What is recall?

Correct positive predictions out of actual positives.

---

# 16. Requirements to Run This Program

# Software Required

## 1. Python

Recommended:

* Python 3.10 or above

---

## 2. Jupyter Notebook or VS Code

You can run this in:

* Jupyter Notebook
* Google Colab
* VS Code
* PyCharm

---

# Required Libraries

Install using:

```bash
pip install numpy pandas scikit-learn
```

---

# Libraries Used

| Library      | Purpose                     |
| ------------ | --------------------------- |
| NumPy        | Numerical operations        |
| Pandas       | Dataset handling            |
| scikit-learn | Machine learning algorithms |

---

# Required Dataset File

You need:

```python
 data6.csv
```

The CSV file must be in same folder as notebook.

---

# 17. How to Run the Program

## Step 1

Install Python.

## Step 2

Install libraries:

```bash
pip install numpy pandas scikit-learn
```

## Step 3

Place:

```python
6Naïve_Bayes.ipynb
```

and:

```python
data6.csv
```

in same folder.

## Step 4

Open Jupyter Notebook.

## Step 5

Run cells one by one.

## Step 6

Enter age and salary when asked.

## Step 7

View prediction result.

---

# 18. Summary

This project:

* Uses Gaussian Naive Bayes algorithm
* Trains on dataset
* Predicts output classes
* Evaluates performance
* Uses confusion matrix
* Accepts user input for prediction

The model is simple, fast, and widely used for classification tasks.

naives formula and define FORMULA TERMS WHAT IT IS CALLED?
ADV AND DISADV , REAL LIFE APPLICATIONS IN BRIEF


What the Formula Terms Mean
Term	   Name	                                Meaning
P(A|B)	Posterior Probability	                Probability of A after B happens
P(B|A)	Likelihood Probability	              Probability of B when A already happened
P(A)	  Prior Probability	                    Initial probability of A
P(B)	  Evidence Probability	                Total probability of B

P(A|B)=\frac{P(B|A)P(A)}{P(B)}


What is it Called?

This formula is called:
Bayes Theorem
Used in Naive Bayes Algorithm

The algorithm is called:

Naive → assumes all features are independent
Bayes → uses Bayes theorem
Simple Example

Suppose:

A = Person has disease
B = Fever symptom

Then:

P(A|B) → Probability person has disease if fever is present.

Advantages of Naive Bayes
Simple and easy to implement
Fast training and prediction
Works well with small datasets
Good for classification problems
Requires less memory
Performs well in text classification

Disadvantages of Naive Bayes
Assumes features are independent
Accuracy may reduce for complex data
Zero frequency problem can occur
Not suitable when features are highly related

Real Life Applications
Application	Use
Spam Email Detection	Detect spam or non-spam emails
Sentiment Analysis	Positive or negative reviews
Medical Diagnosis	Predict diseases from symptoms
Recommendation Systems	Suggest movies/products
Fraud Detection	Detect suspicious transactions
Document Classification	Categorize documents/news
Chatbots	Understand user intent

Short Definition
Naive Bayes Definition

Naive Bayes is a supervised machine learning classification algorithm based on Bayes Theorem that predicts outcomes using probability.