# -*- coding: utf-8 -*-
"""7Term Frequency.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pvt_yHUtTgHnDG429KDz5EP2E3qR_STl
"""

# ----------------------------------------------------------
# STEP 1: Import Libraries
# ----------------------------------------------------------
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk import pos_tag
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

# Download (first time only)
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('wordnet')
nltk.download('punkt_tab')

# ----------------------------------------------------------
# STEP 2: Sample Documents (2 documents)
# ----------------------------------------------------------
documents = [
    "Natural Language Processing is a fascinating field of Artificial Intelligence.",
    "Artificial Intelligence helps computers understand human language."
]

print("\nOriginal Documents:")
for i, doc in enumerate(documents, 1):
    print(f"Doc {i}: {doc}")

# ----------------------------------------------------------
# STEP 3: Tokenization
# ----------------------------------------------------------
print("\nTokenization:")
all_tokens = []
for i, doc in enumerate(documents, 1):
    tokens = word_tokenize(doc)
    all_tokens.append(tokens)
    print(f"Doc {i} Tokens:", tokens)

# ----------------------------------------------------------
# STEP 4: POS Tagging
# ----------------------------------------------------------
print("\nPOS Tagging:")
for i, tokens in enumerate(all_tokens, 1):
    pos_tags = pos_tag(tokens)
    print(f"Doc {i} POS Tags:", pos_tags)

# ----------------------------------------------------------
# STEP 5: Stop Words Removal
# ----------------------------------------------------------
stop_words = set(stopwords.words('english'))
filtered_docs = []

print("\nAfter Stop Words Removal:")
for i, tokens in enumerate(all_tokens, 1):
    filtered = [word for word in tokens if word.lower() not in stop_words]
    filtered_docs.append(filtered)
    print(f"Doc {i}:", filtered)

# ----------------------------------------------------------
# STEP 6: Stemming
# ----------------------------------------------------------
ps = PorterStemmer()
print("\nStemming:")
for i, tokens in enumerate(filtered_docs, 1):
    stemmed = [ps.stem(word) for word in tokens]
    print(f"Doc {i}:", stemmed)

# ----------------------------------------------------------
# STEP 7: Lemmatization
# ----------------------------------------------------------
lemmatizer = WordNetLemmatizer()
print("\nLemmatization:")
for i, tokens in enumerate(filtered_docs, 1):
    lemmatized = [lemmatizer.lemmatize(word) for word in tokens]
    print(f"Doc {i}:", lemmatized)

# ----------------------------------------------------------
# STEP 8: Term Frequency (CountVectorizer)
# ----------------------------------------------------------
cv = CountVectorizer()
tf_matrix = cv.fit_transform(documents)

print("\nTerm Frequency (CountVectorizer):")
print("Feature Names:", cv.get_feature_names_out())
print("TF Matrix:\n", tf_matrix.toarray())

# ----------------------------------------------------------
# STEP 9: TF-IDF Representation
# ----------------------------------------------------------
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(documents)

print("\nTF-IDF Representation:")
print("Feature Names:", tfidf.get_feature_names_out())
print("TF-IDF Matrix:\n", tfidf_matrix.toarray())

# Complete Explanation of Term Frequency NLP Program

## 1. Introduction

This program demonstrates basic Natural Language Processing (NLP) concepts using Python.

It performs:

1. Text preprocessing
2. Tokenization
3. Stopword removal
4. Stemming
5. Lemmatization
6. POS Tagging
7. Count Vectorization
8. TF-IDF (Term Frequency – Inverse Document Frequency)

The code uses Python libraries such as NLTK and Scikit-learn.

---

# 2. What is NLP?

Natural Language Processing (NLP) is a branch of Artificial Intelligence that helps computers understand, process, and analyze human language.

Examples:

* ChatGPT
* Google Translate
* Voice assistants
* Spam detection
* Sentiment analysis
* Text summarization

---

# 3. Overall Flow of the Program

The complete process follows these steps:

1. Import libraries
2. Download required NLP datasets
3. Take sample documents
4. Convert text into tokens
5. Remove stopwords
6. Perform stemming
7. Perform lemmatization
8. Apply POS tagging
9. Convert text into vectors
10. Calculate TF-IDF values
11. Display results

---

# 4. Libraries Required

## A) NLTK

NLTK = Natural Language Toolkit

Used for:

* Tokenization
* Stopword removal
* Stemming
* Lemmatization
* POS tagging

Install:

```bash
pip install nltk
```

---

## B) Scikit-learn

Used for:

* Count Vectorizer
* TF-IDF Vectorizer

Install:

```bash
pip install scikit-learn
```

---

# 5. Requirements to Run the Program

You need:

## Software

1. Python installed
2. Jupyter Notebook or VS Code

---

## Python Libraries

Install using:

```bash
pip install nltk
pip install scikit-learn
```

---

## Internet Connection

Required only first time because NLTK downloads datasets.

---

# 6. Full Code

```python
# ----------------------------------------------------------
# STEP 1: Import Libraries
# ----------------------------------------------------------
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk import pos_tag
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

# Download (first time only)
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('wordnet')
nltk.download('punkt_tab')

# ----------------------------------------------------------
# STEP 2: Sample Documents (2 documents)
# ----------------------------------------------------------
documents = [
    "Natural Language Processing is a fascinating field of Artificial Intelligence.",
    "Artificial Intelligence helps computers understand human language."
]

print("\nOriginal Documents:")
for i, doc in enumerate(documents, start=1):
    print(f"Document {i}: {doc}")

# ----------------------------------------------------------
# STEP 3: Tokenization
# ----------------------------------------------------------
print("\n--- TOKENIZATION ---")
all_tokens = []

for i, doc in enumerate(documents, start=1):
    tokens = word_tokenize(doc)
    all_tokens.append(tokens)

    print(f"\nDocument {i} Tokens:")
    print(tokens)

# ----------------------------------------------------------
# STEP 4: Stopword Removal
# ----------------------------------------------------------
print("\n--- STOPWORD REMOVAL ---")
stop_words = set(stopwords.words('english'))
filtered_docs = []

for i, tokens in enumerate(all_tokens, start=1):
    filtered = [word for word in tokens if word.lower() not in stop_words]
    filtered_docs.append(filtered)

    print(f"\nDocument {i} after Stopword Removal:")
    print(filtered)

# ----------------------------------------------------------
# STEP 5: Stemming
# ----------------------------------------------------------
print("\n--- STEMMING ---")
ps = PorterStemmer()

for i, words in enumerate(filtered_docs, start=1):
    stemmed = [ps.stem(word) for word in words]

    print(f"\nDocument {i} Stemmed Words:")
    print(stemmed)

# ----------------------------------------------------------
# STEP 6: Lemmatization
# ----------------------------------------------------------
print("\n--- LEMMATIZATION ---")
lemmatizer = WordNetLemmatizer()

for i, words in enumerate(filtered_docs, start=1):
    lemmatized = [lemmatizer.lemmatize(word) for word in words]

    print(f"\nDocument {i} Lemmatized Words:")
    print(lemmatized)

# ----------------------------------------------------------
# STEP 7: POS Tagging
# ----------------------------------------------------------
print("\n--- POS TAGGING ---")

for i, words in enumerate(filtered_docs, start=1):
    pos_tags = pos_tag(words)

    print(f"\nDocument {i} POS Tags:")
    print(pos_tags)

# ----------------------------------------------------------
# STEP 8: Convert Documents Back to String
# ----------------------------------------------------------
processed_docs = [' '.join(words) for words in filtered_docs]

# ----------------------------------------------------------
# STEP 9: Count Vectorizer (Term Frequency)
# ----------------------------------------------------------
print("\n--- COUNT VECTORIZER (TERM FREQUENCY) ---")
count_vectorizer = CountVectorizer()
X_count = count_vectorizer.fit_transform(processed_docs)

print("\nFeature Names:")
print(count_vectorizer.get_feature_names_out())

print("\nTerm Frequency Matrix:")
print(X_count.toarray())

# ----------------------------------------------------------
# STEP 10: TF-IDF Vectorizer
# ----------------------------------------------------------
print("\n--- TF-IDF VECTORIZER ---")
tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform(processed_docs)

print("\nTF-IDF Feature Names:")
print(tfidf_vectorizer.get_feature_names_out())

print("\nTF-IDF Matrix:")
print(X_tfidf.toarray())
```

---

# 7. Detailed Theory of Each Concept

# STEP 1: Import Libraries

```python
import nltk
```

Imports the NLTK library.

Purpose:

* Provides NLP tools.

---

```python
from nltk.tokenize import word_tokenize
```

Imports tokenizer.

Purpose:

* Splits sentence into words.

Example:

Input:

```python
"I love AI"
```

Output:

```python
['I', 'love', 'AI']
```

---

```python
from nltk.corpus import stopwords
```

Imports stopwords dataset.

Stopwords are common words like:

* is
* the
* a
* an
* of

These words usually do not add important meaning.

---

```python
from nltk.stem import PorterStemmer
```

Imports stemming tool.

Stemming removes suffixes.

Example:

```python
playing → play
running → run
```

---

```python
from nltk.stem import WordNetLemmatizer
```

Imports lemmatizer.

Lemmatization converts words into meaningful root forms.

Example:

```python
better → good
running → run
```

---

```python
from nltk import pos_tag
```

Used for POS tagging.

POS = Part Of Speech

It identifies:

* Noun
* Verb
* Adjective
* Adverb

Example:

```python
run → Verb
beautiful → Adjective
```

---

```python
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
```

Imports:

1. CountVectorizer
2. TfidfVectorizer

These convert text into numerical vectors.

Machine learning algorithms only understand numbers.

---

# NLTK Downloads

```python
nltk.download('punkt')
```

Downloads tokenizer model.

---

```python
nltk.download('stopwords')
```

Downloads stopwords dataset.

---

```python
nltk.download('averaged_perceptron_tagger')
```

Downloads POS tagging model.

---

```python
nltk.download('wordnet')
```

Downloads dictionary for lemmatization.

---

# STEP 2: Documents

```python
documents = [
    "Natural Language Processing is a fascinating field of Artificial Intelligence.",
    "Artificial Intelligence helps computers understand human language."
]
```

Creates two sample text documents.

These are used as input data.

---

# STEP 3: Tokenization

## Theory

Tokenization means breaking text into smaller units called tokens.

Tokens may be:

* Words
* Sentences
* Characters

Example:

Sentence:

```python
"AI is powerful"
```

Tokens:

```python
['AI', 'is', 'powerful']
```

---

## Code Explanation

```python
all_tokens = []
```

Creates empty list.

Purpose:

* Store tokenized documents.

---

```python
for i, doc in enumerate(documents, start=1):
```

Loops through each document.

`enumerate()` gives:

* Index
* Document

---

```python
tokens = word_tokenize(doc)
```

Splits document into words.

---

```python
all_tokens.append(tokens)
```

Stores tokens inside list.

---

# STEP 4: Stopword Removal

# Theory

Stopwords are very common words.

Examples:

* the
* is
* a
* of

They usually do not help in text analysis.

Removing them:

* Reduces noise
* Improves efficiency
* Improves accuracy

---

## Code Explanation

```python
stop_words = set(stopwords.words('english'))
```

Gets English stopwords.

`set()` improves searching speed.

---

```python
filtered_docs = []
```

Stores processed words.

---

```python
filtered = [word for word in tokens if word.lower() not in stop_words]
```

List comprehension.

Meaning:

* Keep only important words.
* Remove stopwords.

---

# STEP 5: Stemming

# Theory

Stemming reduces a word to its root form.

Example:

```python
playing → play
studies → studi
```

It may produce non-dictionary words.

---

## Code Explanation

```python
ps = PorterStemmer()
```

Creates stemming object.

---

```python
stemmed = [ps.stem(word) for word in words]
```

Applies stemming to every word.

---

# STEP 6: Lemmatization

# Theory

Lemmatization converts words into meaningful base words.

More accurate than stemming.

Example:

```python
running → run
better → good
```

---

## Code Explanation

```python
lemmatizer = WordNetLemmatizer()
```

Creates lemmatizer object.

---

```python
lemmatized = [lemmatizer.lemmatize(word) for word in words]
```

Converts words into base forms.

---

# Difference Between Stemming and Lemmatization

| Stemming                 | Lemmatization       |
| ------------------------ | ------------------- |
| Faster                   | Slower              |
| Less accurate            | More accurate       |
| May create invalid words | Creates valid words |
| Uses rules               | Uses dictionary     |

---

# STEP 7: POS Tagging

# Theory

POS Tagging identifies grammatical role of each word.

Examples:

| Word      | Tag | Meaning   |
| --------- | --- | --------- |
| run       | VB  | Verb      |
| dog       | NN  | Noun      |
| beautiful | JJ  | Adjective |

---

## Code Explanation

```python
pos_tags = pos_tag(words)
```

Assigns grammar tags.

Example Output:

```python
[('Artificial', 'JJ'), ('Intelligence', 'NN')]
```

---

# STEP 8: Convert Back to String

```python
processed_docs = [' '.join(words) for words in filtered_docs]
```

Joins list of words into sentence.

Why?

Because vectorizers require string input.

---

# STEP 9: Count Vectorizer

# Theory

CountVectorizer converts text into numbers.

It counts frequency of each word.

This is called:

## Term Frequency (TF)

Example:

Sentence:

```python
AI is AI
```

Vocabulary:

```python
[AI, is]
```

Vector:

```python
[2,1]
```

Meaning:

* AI appears 2 times
* is appears 1 time

---

## Code Explanation

```python
count_vectorizer = CountVectorizer()
```

Creates vectorizer object.

---

```python
X_count = count_vectorizer.fit_transform(processed_docs)
```

Two operations:

### fit()

Learns vocabulary.

### transform()

Converts documents into matrix.

---

```python
count_vectorizer.get_feature_names_out()
```

Returns all unique words.

---

```python
X_count.toarray()
```

Converts sparse matrix into normal array.

---

# STEP 10: TF-IDF

# Theory

TF-IDF means:

## Term Frequency – Inverse Document Frequency

Used to find importance of words.

Formula:

genui{"math_block_widget_always_prefetch_v2":{"content":"TF\text{-}IDF = TF \times IDF"}}

Where:

## TF

Counts frequency of word in document.

Formula:

genui{"math_block_widget_always_prefetch_v2":{"content":"TF = \frac{\text{Number of times word appears}}{\text{Total words in document}}"}}

---

## IDF

Measures uniqueness of word.

Formula:

genui{"math_block_widget_always_prefetch_v2":{"content":"IDF = \log\left(\frac{\text{Total Documents}}{\text{Documents containing the word}}\right)"}}

---

## Important Idea

* Common words get lower score.
* Rare important words get higher score.

---

## Code Explanation

```python
tfidf_vectorizer = TfidfVectorizer()
```

Creates TF-IDF object.

---

```python
X_tfidf = tfidf_vectorizer.fit_transform(processed_docs)
```

Calculates TF-IDF scores.

---

```python
X_tfidf.toarray()
```

Displays TF-IDF matrix.

---

# 8. Sparse Matrix

Vectorizers return sparse matrix.

Sparse matrix stores only non-zero values.

Why?

Because most words are absent in most documents.

This saves:

* Memory
* Computation time

---

# 9. Real Life Applications

| Concept          | Applications             |
| ---------------- | ------------------------ |
| Tokenization     | Chatbots, search engines |
| Stopword Removal | Search optimization      |
| Stemming         | Search engines           |
| Lemmatization    | Text understanding       |
| POS Tagging      | Grammar checking         |
| TF-IDF           | Document ranking         |
| NLP              | ChatGPT, Alexa, Siri     |

---

# 10. Advantages of TF-IDF

1. Simple
2. Efficient
3. Removes importance of common words
4. Useful in search engines
5. Good for text classification

---

# 11. Limitations of TF-IDF

1. Does not understand meaning
2. Ignores context
3. Cannot understand sarcasm
4. Word order ignored

---

# 12. Time Complexity

| Operation        | Complexity |
| ---------------- | ---------- |
| Tokenization     | O(n)       |
| Stopword Removal | O(n)       |
| Stemming         | O(n)       |
| Lemmatization    | O(n)       |
| Count Vectorizer | O(n × v)   |
| TF-IDF           | O(n × v)   |

Where:

* n = total words
* v = vocabulary size

---

# 13. Viva Questions and Answers

## Q1. What is NLP?

NLP is a branch of AI that allows computers to understand human language.

---

## Q2. What is tokenization?

Breaking text into smaller parts called tokens.

---

## Q3. What are stopwords?

Common words with less importance like is, the, a.

---

## Q4. Difference between stemming and lemmatization?

Stemming removes suffixes using rules.
Lemmatization returns meaningful base words using dictionary.

---

## Q5. What is TF-IDF?

A technique that measures importance of words in documents.

---

## Q6. Why convert text into vectors?

Machine learning models understand only numbers.

---

## Q7. What is CountVectorizer?

Converts text into word frequency matrix.

---

## Q8. Why use sparse matrix?

To save memory.

---

# 14. Simple Algorithm

## Algorithm

1. Start
2. Import libraries
3. Download datasets
4. Take input documents
5. Tokenize documents
6. Remove stopwords
7. Apply stemming
8. Apply lemmatization
9. Apply POS tagging
10. Convert text into vectors
11. Compute TF-IDF
12. Display results
13. Stop

---

# 15. Conclusion

This program demonstrates the complete NLP preprocessing pipeline.

It shows how:

* Text is cleaned
* Words are processed
* Text is converted into numbers
* Important words are identified using TF-IDF

These techniques are widely used in:

* Search engines
* Chatbots
* Recommendation systems
* AI assistants
* Spam filtering
* Text classification




STEP 9: Count Vectorizer (Term Frequency)
Theory

Count Vectorizer converts text data into numerical form.

It counts how many times each word appears in a document.

Machine learning models cannot understand text directly, so Count Vectorizer converts words into numbers.

Example:

Sentence:

"AI is AI"

Vocabulary:

[AI, is]

Vector:

[2,1]

Meaning:

AI appears 2 times
is appears 1 time
Working Steps
Take text documents
Split text into words
Create vocabulary of unique words
Count frequency of each word
Create matrix of counts
Formula

Term Frequency:

TF=Count of a word in a document

Advantages
Simple and easy to implement
Fast processing
Converts text into numerical form
Useful for basic NLP tasks
Works well for small datasets

Disadvantages
Ignores meaning of words
Ignores word order
Large vocabulary increases memory usage
Common words may dominate
Cannot understand context


Real Life Applications
Spam Email Detection
Sentiment Analysis
Search Engines
Chatbots
Document Classification
News Categorization
Recommendation Systems
Text Mining