# -*- coding: utf-8 -*-
"""8Data Visualization1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XX8dlvmPc8YZwemP1wYFKs13xwDzYNoz
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dataset=pd.read_csv('data8.csv')
dataset

sns.distplot(dataset['Fare'])

"""The Dist Plot
The distplot() shows the histogram distribution of data for a single column. The column name is passed as a parameter to the distplot() function. Let's see how the price of the ticket for each passenger is distributed.
"""

sns.distplot(dataset['Fare'], kde=False)

"""kde(Guassian kernal Density Estimate):
Now you can see there is no line for the kernel density estimation on the plot.

You can also pass the value for the bins parameter in order to see more or less details in the graph. Take a look at he following script:
"""

sns.distplot(dataset['Fare'], kde=False, bins=10)

"""Bins (Height of the bar plot which means how many datapoint are threr in that particular bin)"""

sns.jointplot(x='Age', y='Fare', data=dataset)

"""The Joint Plot
The jointplot()is used to display the mutual distribution of each column. You need to pass three parameters to jointplot. The first parameter is the column name for which you want to display the distribution of data on x-axis. The second parameter is the column name for which you want to display the distribution of data on y-axis. Finally, the third parameter is the name of the data frame.
"""

sns.pairplot(dataset)

"""The paitplot() is a type of distribution plot that basically plots a joint plot for all the possible combination of numeric and Boolean columns in your dataset. You only need to pass the name of your dataset as the parameter to the pairplot() function as shown below:"""

sns.rugplot(dataset['Fare'])

"""he rugplot() is used to draw small bars along x-axis for each point in the dataset. To plot a rug plot, you need to pass the name of the column. Let's plot a rug plot for fare.From the output, you can see that as was the case with the distplot(), most of the instances for the fares have values between 0 and 100."""

sns.barplot(x='Sex', y='Age', data=dataset)

"""The barplot() is used to display the mean value for each value in a categorical column, against a numeric column. The first parameter is the categorical column, the second parameter is the numeric column while the third parameter is the dataset. For instance, if you want to know the mean value of the age of the male and female passengers,"""

sns.countplot(x='Fare', data=dataset)

sns.boxplot(x='Sex', y='Age', data=dataset)

sns.boxplot(x='Survived', y='Fare', data=dataset)

sns.boxplot(x='Sex', y='Age', data=dataset, hue="Survived")

"""Now in addition to the information about the age of each gender, you can also see the distribution of the passengers who survived. For instance, you can see that among the male passengers, on average more younger people survived as compared to the older ones. Similarly, you can see that the variation among the age of female passengers who did not survive is much greater than the age of the surviving female passengers."""

sns.violinplot(x='Sex', y='Age', data=dataset, hue='Survived')

""" The violinplot() function is used to plot the violin plot. Like the box plot, the first parameter is the categorical column, the second parameter is the numeric column while the third parameter is the dataset. if you look at the bottom of the violin plot for the males who survived (left-orange), you can see that it is thicker than the bottom of the violin plot for the males who didn't survive (left-blue). This means that the number of young male passengers who survived is greater than the number of young male passengers who did not survive. The violin plots convey a lot of information, however, on the downside, it takes a bit of time and effort to understand the violin plots."""

sns.stripplot(x='Sex', y='Age', data=dataset)

"""The stripplot() function is used to plot the violin plot. Like the box plot, the first parameter is the categorical column, the second parameter is the numeric column while the third parameter is the dataset."""

sns.histplot(data=dataset,x='Fare',y='Survived')

# Data Visualization using Python – Complete Theory, Steps, and Line-by-Line Code Explanation

## 1. What is Data Visualization?

Data Visualization means representing data in graphical form such as:

* Graphs
* Charts
* Histograms
* Box plots
* Scatter plots

It helps us:

* Understand data easily
* Find patterns
* Detect outliers
* Compare values
* Analyze relationships between columns
* Make better decisions

---

# 2. Why is Data Visualization Important?

Data visualization is used because raw data is difficult to understand.

Example:
If a dataset contains 10,000 rows, reading numbers manually is difficult.
Graphs help us understand:

* Which values are high or low
* Distribution of data
* Trends
* Correlation between features

---

# 3. Libraries Required

Your notebook uses these Python libraries:

| Library    | Purpose                               |
| ---------- | ------------------------------------- |
| pandas     | Used for loading and handling dataset |
| seaborn    | Used for statistical visualization    |
| matplotlib | Used for plotting graphs              |

---

# 4. Requirements to Run This Project

## Software Required

You need:

1. Python installed
2. Jupyter Notebook OR Google Colab
3. Dataset file (`data8.csv`)

---

## Install Required Libraries

Open terminal or command prompt and run:

```bash
pip install pandas
pip install matplotlib
pip install seaborn
```

OR

```bash
pip install pandas matplotlib seaborn
```

---

# 5. Steps to Run the Project

## Step 1: Install Python

Download Python from:

* Python Official Website

---

## Step 2: Install Jupyter Notebook

```bash
pip install notebook
```

Run notebook:

```bash
jupyter notebook
```

---

## Step 3: Place Dataset File

Keep:

```text
8Data_Visualization1.ipynb
```

and

```text
data8.csv
```

inside same folder.

---

## Step 4: Run Cells One by One

Execute notebook cells from top to bottom.

Shortcut:

```text
Shift + Enter
```

---

# 6. Dataset Used

Your code appears to use Titanic dataset columns:

| Column   | Meaning         |
| -------- | --------------- |
| Fare     | Ticket fare     |
| Age      | Passenger age   |
| Sex      | Male/Female     |
| Survived | Survival status |

---

# 7. Complete Code Explanation

---

# Cell 1

```python
import pandas as pd
```

## Explanation

* `import` is used to include a library.
* `pandas` is a Python library for data handling.
* `as pd` creates a short name `pd`.

So instead of writing:

```python
pandas.read_csv()
```

we write:

```python
pd.read_csv()
```

---

# Missing Imports

Your notebook also uses seaborn.
Normally we should write:

```python
import seaborn as sns
import matplotlib.pyplot as plt
```

## Why?

| Library    | Use                   |
| ---------- | --------------------- |
| seaborn    | Advanced graphs       |
| matplotlib | Base plotting library |

---

# Cell 2

```python
dataset=pd.read_csv('data8.csv')
```

## Line-by-Line Explanation

### `pd.read_csv()`

* Reads CSV file
* Converts file into DataFrame

A DataFrame is:

* Table-like structure
* Rows and columns

### `'data8.csv'`

Name of dataset file.

### `dataset =`

Stores loaded data into variable named `dataset`.

---

## What Happens Internally?

1. Python opens CSV file
2. Reads rows and columns
3. Converts into DataFrame
4. Stores in memory

---

# Dist Plot

# Cell 3

```python
sns.distplot(dataset['Fare'])
```

## Theory

A Distribution Plot shows:

* How data is distributed
* Frequency of values
* Density of values

It combines:

* Histogram
* KDE curve

---

## Line-by-Line Explanation

### `sns`

Alias of seaborn.

### `distplot()`

Function used to create distribution plot.

### `dataset['Fare']`

Selects Fare column from dataset.

---

## Output Meaning

* Bars show frequency
* Curve shows smooth probability distribution

---

## Real Life Example

Used in:

* Salary distribution
* Marks analysis
* Product price analysis

---

# KDE Plot

# Cell 4

```python
sns.distplot(dataset['Fare'], kde=False)
```

## Theory

KDE means:

Kernel Density Estimate

It is a smooth probability curve.

Here:

```python
kde=False
```

means:

* Do not show KDE curve
* Show only histogram

---

## Output

Only bars are displayed.

---

# Dist Plot with Bins

# Cell 5

```python
sns.distplot(dataset['Fare'], kde=False, bins=10)
```

## Theory

Bins means:

* Number of intervals
* Number of histogram divisions

Example:

If values are from 0 to 100:

10 bins means:

```text
0-10
10-20
20-30
...
```

---

## Explanation

### `bins=10`

Divides graph into 10 bars.

---

## Why Bins Important?

* Too many bins → noisy graph
* Too few bins → loss of information

---

# Joint Plot

# Cell 6

```python
sns.jointplot(x='Age', y='Fare', data=dataset)
```

## Theory

Joint Plot shows:

* Relationship between two variables
* Distribution of both variables

It contains:

* Scatter plot
* Histograms

---

## Explanation

### `x='Age'`

Age on x-axis.

### `y='Fare'`

Fare on y-axis.

### `data=dataset`

Uses dataset DataFrame.

---

## What Does It Show?

* Whether Age affects Fare
* Distribution of Age
* Distribution of Fare

---

## Real Life Applications

* Height vs weight
* Experience vs salary
* Study hours vs marks

---

# Pair Plot

# Cell 7

```python
sns.pairplot(dataset)
```

## Theory

Pair plot creates:

* Multiple scatter plots
* Multiple histograms

It compares every numerical column with every other column.

---

## Why Important?

Used for:

* Correlation analysis
* Feature selection
* Data exploration

---

## Output

You get matrix of plots.

Diagonal:

* Histograms

Other cells:

* Scatter plots

---

# Rug Plot

# Cell 8

```python
sns.rugplot(dataset['Fare'])
```

## Theory

Rug plot:

* Draws small vertical lines
* Each line represents one data point

---

## Why Used?

To see:

* Density of values
* Exact location of observations

---

## Explanation

### `dataset['Fare']`

Uses Fare column.

---

# Bar Plot

# Cell 9

```python
sns.barplot(x='Sex', y='Age', data=dataset)
```

## Theory

Bar plot:

* Displays average values
* Compares categories

---

## Explanation

### `x='Sex'`

Male/Female categories.

### `y='Age'`

Average age values.

### `data=dataset`

Source dataset.

---

## What Happens Internally?

Seaborn:

1. Groups data by gender
2. Calculates mean age
3. Draws bars

---

## Real Life Applications

* Average salary by department
* Average marks by class
* Average sales by region

---

# Count Plot

# Cell 10

```python
sns.countplot(x='Fare', data=dataset)
```

## Theory

Count plot:

* Counts occurrences
* Displays frequency of categories

---

## Explanation

### `x='Fare'`

Fare values on x-axis.

### `data=dataset`

Dataset source.

---

## Note

Count plot is generally better for categorical data.
Using continuous Fare values may create crowded graph.

---

# Box Plot

# Cell 11

```python
sns.boxplot(x='Sex', y='Age', data=dataset)
```

## Theory

Box plot shows:

* Minimum value
* Maximum value
* Median
* Quartiles
* Outliers

---

## Box Plot Components

| Component       | Meaning         |
| --------------- | --------------- |
| Box             | Middle 50% data |
| Line inside box | Median          |
| Whiskers        | Range           |
| Dots            | Outliers        |

---

## Explanation

### `x='Sex'`

Groups by gender.

### `y='Age'`

Shows age distribution.

---

## Why Important?

Very useful for:

* Detecting outliers
* Comparing distributions

---

# Box Plot with Survival

# Cell 12

```python
sns.boxplot(x='Survived', y='Fare', data=dataset)
```

## Theory

Compares fare distribution between:

* Survived passengers
* Non-survived passengers

---

## Interpretation

Can help analyze:

* Did higher fare passengers survive more?

---

# Box Plot with Hue

# Cell 13

```python
sns.boxplot(x='Sex', y='Age', data=dataset, hue="Survived")
```

## Theory

`hue` adds another category.

Now graph compares:

* Gender
* Age
* Survival status

all together.

---

## Explanation

### `hue='Survived'`

Adds color grouping based on survival.

---

## Why Useful?

Helps perform multi-dimensional analysis.

---

# Violin Plot

# Cell 14

```python
sns.violinplot(x='Sex', y='Age', data=dataset, hue='Survived')
```

## Theory

Violin plot combines:

* Box plot
* KDE distribution

Shape width represents:

* Density of data

---

## Difference Between Boxplot and Violinplot

| Boxplot         | Violinplot              |
| --------------- | ----------------------- |
| Shows quartiles | Shows full distribution |
| Simpler         | More detailed           |

---

## Why Used?

Useful when we want:

* Statistical summary
* Data distribution together

---

# Strip Plot

# Cell 15

```python
sns.stripplot(x='Sex', y='Age', data=dataset)
```

## Theory

Strip plot:

* Displays individual data points
* Useful for small datasets

---

## Explanation

Each dot:

* Represents one passenger

---

## Why Useful?

Helps visualize:

* Spread of data
* Clustering
* Outliers

---

# Hist Plot

# Cell 16

```python
sns.histplot(data=dataset,x='Fare',y='Survived')
```

## Theory

Histogram:

* Shows frequency distribution
* Helps understand data spread

---

## Explanation

### `x='Fare'`

Fare values on x-axis.

### `y='Survived'`

Survival values on y-axis.

---

# 8. Types of Data Visualization Used

| Plot        | Purpose                            |
| ----------- | ---------------------------------- |
| Dist Plot   | Distribution analysis              |
| Joint Plot  | Relationship between two variables |
| Pair Plot   | Compare all numeric columns        |
| Rug Plot    | Show individual data points        |
| Bar Plot    | Compare averages                   |
| Count Plot  | Frequency counting                 |
| Box Plot    | Detect outliers and spread         |
| Violin Plot | Distribution + box plot            |
| Strip Plot  | Individual observations            |
| Hist Plot   | Frequency distribution             |

---

# 9. Complete Workflow of Data Visualization

## Step 1: Import Libraries

```python
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
```

---

## Step 2: Load Dataset

```python
dataset=pd.read_csv('data8.csv')
```

---

## Step 3: Explore Data

```python
dataset.head()
dataset.info()
dataset.describe()
```

---

## Step 4: Create Visualizations

Use:

* Histogram
* Boxplot
* Pairplot
* Violinplot
  etc.

---

## Step 5: Analyze Results

Find:

* Trends
* Patterns
* Correlations
* Outliers

---

# 10. Advantages of Data Visualization

* Easy understanding
* Faster analysis
* Better decision making
* Detect hidden patterns
* Improves presentation

---

# 11. Limitations

* Wrong graph may mislead
* Large datasets may become cluttered
* Requires proper interpretation

---

# 12. Real Life Applications

## Healthcare

* Disease analysis
* Patient statistics

## Finance

* Stock market trends
* Profit analysis

## Business

* Sales analysis
* Customer behavior

## Education

* Student performance analysis

## Machine Learning

* Feature analysis
* Data preprocessing

---

# 13. Viva Questions with Answers

## Q1. What is data visualization?

Data visualization is graphical representation of data using charts and plots.

---

## Q2. Why do we use seaborn?

Seaborn provides advanced statistical visualizations with attractive designs.

---

## Q3. Difference between matplotlib and seaborn?

| Matplotlib      | Seaborn                       |
| --------------- | ----------------------------- |
| Basic plotting  | Advanced statistical plotting |
| More coding     | Easier syntax                 |
| Less attractive | Better default design         |

---

## Q4. What is KDE?

Kernel Density Estimate is a smooth probability density curve.

---

## Q5. What are outliers?

Outliers are abnormal values significantly different from other values.

---

## Q6. What is a box plot?

A box plot is used to visualize distribution, quartiles, median, and outliers.

---

## Q7. What is pairplot used for?

Pairplot is used to compare all numerical columns together.

---

# 14. Important Concepts Summary

| Concept      | Meaning                        |
| ------------ | ------------------------------ |
| DataFrame    | Table structure in pandas      |
| KDE          | Smooth probability curve       |
| Histogram    | Frequency distribution         |
| Outlier      | Abnormal value                 |
| Correlation  | Relationship between variables |
| Distribution | Spread of data                 |

---

# 15. Final Conclusion

This notebook demonstrates:

* Loading data using pandas
* Visualizing data using seaborn
* Understanding distributions
* Comparing categories
* Finding relationships between variables
* Detecting patterns and outliers

It is an important part of:

* Data Science
* Machine Learning
* Data Analytics
* Business Intelligence