# -*- coding: utf-8 -*-
"""9Data Visualization2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PzYYml0dk_uZxOdrSBpEi3c3jRO5LE00
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dataset=pd.read_csv('data9.csv')
dataset

sns.boxplot(x='Sex', y='Age', data=dataset)

"""The box plot is used to display the distribution of the categorical data in the form of quartiles. The center of the box shows the median value. The value from the lower whisker to the bottom of the box shows the first quartile. From the bottom of the box to the middle of the box lies the second quartile. From the middle of the box to the top of the box lies the third quartile and finally from the top of the box to the top whisker lies the last quartile.
Now let's plot a box plot that displays the distribution for the age with respect to each gender. You need to pass the categorical column as the first parameter (which is sex in our case) and the numeric column (age in our case) as the second parameter. Finally, the dataset is passed as the third parameter

Let's try to understand the box plot for female. The first quartile starts at around 5 and ends at 22 which means that 25% of the passengers are aged between 5 and 25. The second quartile starts at around 23 and ends at around 32 which means that 25% of the passengers are aged between 23 and 32. Similarly, the third quartile starts and ends between 34 and 42, hence 25% passengers are aged within this range and finally the fourth or last quartile starts at 43 and ends around 65.

If there are any outliers or the passengers that do not belong to any of the quartiles, they are called outliers and are represented by dots on the box plot.

You can make your box plots more fancy by adding another layer of distribution. For instance, if you want to see the box plots of forage of passengers of both genders, along with the information about whether or not they survived, you can pass the survived as value to the hue parameter as shown below:
"""

sns.boxplot(x='Sex', y='Age', data=dataset, hue="Survived")

"""Now in addition to the information about the age of each gender, you can also see the distribution of the passengers who survived. For instance, you can see that among the male passengers, on average more younger people survived as compared to the older ones. Similarly, you can see that the variation among the age of female passengers who did not survive is much greater than the age of the surviving female passengers.

Boxplot is a very interesting plot that basically plots a 5 number summary. to get 5 number summary some terms we need to describe.
Median – Middle value in series after sorting
Percentile – Gives any number which is number of values present before this percentile like for example 50 under 25th percentile so it explains total of 50 values are there below 25th percentile
Minimum and Maximum – These are not minimum and maximum values, rather they describe the lower and upper boundary of standard deviation which is calculated using Interquartile range(IQR).
"""

sns.boxplot(x="Age", y="Fare", hue="Survived",data=dataset,linewidth=3)

sns.boxplot(x='Sex', y='Age', data=dataset, notch=1)

sns.boxplot(x='Sex', y='Age', data=dataset, notch=1, bootstrap=5)

sns.boxplot(data=dataset, orient="v")

sns.boxplot(data=dataset, orient="h")

plt.boxplot(dataset['Fare'], notch=10, vert=True, patch_artist=True, tick_labels=['Fare'])

sns.boxplot(data=dataset, x="Age", y="Fare", hue='Pclass', palette=None)

This notebook focuses on Data Visualization using the Seaborn and Matplotlib libraries, specifically exploring Box Plots to analyze the Titanic dataset (or a similar dataset named data9.csv).

1. Theory: Understanding Box Plots
A Box Plot (or Box-and-Whisker Plot) is a graphical representation of the distribution of a dataset. It is based on a 5-number summary:

Minimum: The lowest data point (excluding outliers).

First Quartile (Q1/25th Percentile): 25% of the data falls below this value.

Median (Q2/50th Percentile): The middle value of the dataset.

Third Quartile (Q3/75th Percentile): 75% of the data falls below this value.

Maximum: The highest data point (excluding outliers).

Key Concepts:

Interquartile Range (IQR): The "box" itself represents the IQR (Q3−Q1), which contains the middle 50% of the data.

Whiskers: The lines extending from the box. They typically represent the range of the data within 1.5×IQR from the quartiles.

Outliers: Individual points plotted outside the whiskers. They represent data points that are significantly different from the rest.

Notch: A narrowing of the box around the median. If the notches of two boxes do not overlap, it suggests the medians are significantly different.

2. Steps Involved
Environment Setup: Importing necessary libraries for data handling (pandas, numpy) and visualization (matplotlib, seaborn).

Data Acquisition: Loading the dataset from a CSV file into a Pandas DataFrame.

Exploratory Data Analysis (EDA) via Box Plots:

Comparing a categorical variable (e.g., Sex) against a numerical variable (e.g., Age).

Adding a third dimension (e.g., Survived) using the hue parameter to see how survival varies across gender and age.

Customization: Experimenting with plot aesthetics like line thickness, orientation (vertical vs. horizontal), and notched boxes.

3. Line-by-Line Code Explanation
Cell 0: Imports
Python
import pandas as pd     # For data manipulation and analysis
import numpy as np      # For numerical operations
import matplotlib.pyplot as plt  # Basic plotting library
import seaborn as sns   # Advanced visualization library built on Matplotlib
Cell 1: Loading Data
Python
dataset = pd.read_csv('data9.csv') # Reads the CSV file into a DataFrame
dataset                            # Displays the first and last few rows of the data
Cell 2: Simple Box Plot
Python
sns.boxplot(x='Sex', y='Age', data=dataset)
# x: The categorical column (Gender)
# y: The numerical column (Age)
# data: The source DataFrame
Cell 5: Box Plot with Hue
Python
sns.boxplot(x='Sex', y='Age', data=dataset, hue="Survived")
# hue="Survived": Splits each 'Sex' box into two (Survived vs Not Survived) for comparison.
Cell 8: Detailed Comparison
Python
sns.boxplot(x="Age", y="Fare", hue="Survived", data=dataset, linewidth=3)
# linewidth=3: Increases the thickness of the box and whisker lines.
Cells 9 & 10: Notched Plots
Python
sns.boxplot(x='Sex', y='Age', data=dataset, notch=1)
# notch=1: Adds a "waist" to the box at the median to indicate confidence intervals.
Cells 11 & 12: Orientation
Python
sns.boxplot(data=dataset, orient="v") # Plots all numerical columns vertically
sns.boxplot(data=dataset, orient="h") # Plots all numerical columns horizontally
Cell 13: Matplotlib Box Plot
Python
plt.boxplot(dataset['Fare'], notch=10, vert=True, patch_artist=True, tick_labels=['Fare'])
# This uses the base Matplotlib library instead of Seaborn.
# patch_artist=True: Allows the box to be filled with color.
4. What do you require to run this?
To run this code successfully, you need the following:

Python Environment: An installation of Python (3.7 or higher recommended), such as Anaconda or a standalone version.

Libraries:

pandas: pip install pandas

numpy: pip install numpy

matplotlib: pip install matplotlib

seaborn: pip install seaborn

Data File: A file named data9.csv located in the same directory as your script/notebook. Based on the code, this file must contain at least these columns:

Sex (Categorical: e.g., 'male', 'female')

Age (Numerical)

Survived (Categorical/Binary: 0 or 1)

Fare (Numerical)

Pclass (Categorical/Ordinal)

IDE: Jupyter Notebook, JupyterLab, VS Code (with Python extension), or Google Colab.


The Titanic dataset is one of the most famous datasets in the world of data science and machine learning. It contains real-life data about the passengers who were on board the RMS Titanic when it sank in 1912 after hitting an iceberg.

1. What is it used for?
In data science, it is primarily used as a "beginner" project to practice binary classification. The goal is typically to use information like age, sex, and class to predict whether a passenger survived or not.

2. Key Features (Columns)
The dataset usually includes the following information for each passenger:

Survived: Whether the person lived (1) or died (0).

Pclass (Passenger Class): Socio-economic status (1st, 2nd, or 3rd class).

Sex: Gender of the passenger.

Age: How old the passenger was.

SibSp: Number of siblings or spouses on board.

Parch: Number of parents or children on board.

Fare: How much they paid for their ticket.

Embarked: The port where they got on the ship (C = Cherbourg, Q = Queenstown, S = Southampton).

3. Why is it popular?
Simple yet Complex: It is small enough to handle easily but has "missing data" (like many missing ages) and a mix of numbers and categories, making it perfect for learning how to clean and analyze data.

Sociological Insights: It allows you to visualize trends, such as the "women and children first" policy or how survival rates were much higher for those in first class compared to third class.




This practical, which focuses on data visualization using Box Plots via Seaborn and Matplotlib, is a fundamental skill in data science. Below are the advantages, disadvantages, and real-world applications of this specific approach.

1. Advantages
Identifying Outliers: Box plots are the most effective way to visually spot "outliers" (data points that are unusually high or low). In the Titanic data, this helps identify people who paid an extreme fare or were exceptionally old.

Comparing Groups: It is very easy to compare distributions across categories (e.g., comparing the age range of Men vs. Women or Survivors vs. Non-survivors) side-by-side.

Summary at a Glance: Instead of looking at thousands of rows, you get a "5-number summary" (Min, Q1, Median, Q3, Max) in one simple visual.

Clean and Standardized: Libraries like Seaborn handle complex calculations (like calculating the Interquartile Range) automatically, saving time and reducing human error.

Handling Skewness: It clearly shows if data is skewed (e.g., if the median is closer to the bottom, the data is "right-skewed").

2. Disadvantages
Hides Sample Size: A box plot for 10 people looks the same as a box plot for 1,000 people. You cannot see the underlying number of data points (unless you add a "swarm plot" or "strip plot" over it).

Hides Distribution Shape: A box plot cannot tell you if the data has two peaks (bimodal). It only shows quartiles. For example, a "Violin Plot" is often better for seeing the exact shape of the distribution.

Not for Small Datasets: If you only have 5 or 10 data points, a box plot can be misleading as quartiles are not meaningful with very little data.

Static Nature: The basic plots shown in the code are static. In modern web apps, users often prefer interactive plots (like Plotly) where they can hover over a box to see exact values.

3. Real-Life Applications
The techniques used in this Titanic practical are applied across many industries:

Healthcare & Pharmaceuticals: * Comparing the recovery time of patients across different age groups or different treatments.

Identifying outliers in blood pressure or heart rate data that might indicate a medical emergency.

Finance & Banking: * Analyzing the "Fare" equivalent in banking: comparing credit scores or spending habits across different customer segments (Gold vs. Platinum members).

Detecting fraudulent transactions (outliers in spending patterns).

E-Commerce & Retail: * Analyzing the delivery time of products across different regions.

Comparing the prices of products in different categories to find "premium" or "budget" outliers.

Manufacturing Quality Control:

Monitoring the dimensions of parts produced on a factory line. If the "box" shifts or many "dots" (outliers) appear, it indicates a machine needs repair.

Human Resources (HR):

Comparing salary distributions across different departments (Engineering vs. Marketing) to ensure pay equity.